apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_URI: "mongodb://{{ .Release.Name }}-mongo-0.{{ .Release.Name }}-mongo.{{ .Release.Namespace }}.svc.cluster.local:27017,{{ .Release.Name }}-mongo-1.{{ .Release.Name }}-mongo.{{ .Release.Namespace }}.svc.cluster.local:27017/{{ .Values.backend.database }}?replicaSet=rs0"
  JWT_SECRET_KEY: "{{ .Values.backend.jwtSecret }}"

