apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017

